# Generated by Django 6.0.2 on 2026-02-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
    ]
