# Generated by Django 6.0.2 on 2026-02-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.SlugField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
